apiversion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: {{ .Values.environment }}-testapp
    namespace: {{ .Release.Namespace }}
    labels:
        app: {{ .Values.environment }}-testapp
        env: {{ .Values.environment }}
spec:
    maxReplicas: {{ .Values.maxReplicaCount }}
    minReplicas: {{ .Values.replicaCount }}
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: {{ .Values.environment }}-testapp
    metrics:
    - resource:
        name: cpu
        target:
            averageUtilization: 75
            type: Utilization
      type: Resource