apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
    name: {{ .Values.environment }}-testapp
    namespace: {{ .Release.Namespace }}
spec:
    selector:
        istio: ingressgateway
    servers:
    - port:
        number: 80
        name: test1-http
        protocol: HTTP
    hosts:
    - {{ .Values.environment }}.newapp.com