name: Docker image build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REPOSITORY: # TODO: update Artifact Registry

jobs:

  build:

    runs-on: python3

    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build -t $REPOSITORY/testapp:$GITHUB_SHA .
    
    - name: Upload docker image to registry
      run: docker push $REPOSITORY/testapp:$GITHUB_SHA
